import { NextRequest, NextResponse } from "next/server";
import { adminDb, requireAdmin } from "@/lib/firebaseAdmin";
import { getClaude, CLAUDE_MODEL } from "@/lib/claude";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

interface GeneratedFaq {
  question: string;
  answer: string;
  category: string;
  topic_summary?: string;
}

const SYSTEM = `Bạn là chuyên viên phân tích dữ liệu của Phòng Tuyển sinh đại học.
Hãy đọc danh sách các câu hỏi gần đây của thí sinh/phụ huynh và:
1. Tổng hợp những CHỦ ĐỀ được hỏi nhiều nhất hoặc được quan tâm nhất.
2. Với mỗi chủ đề, soạn 1 câu hỏi đại diện rõ ràng + câu trả lời ngắn gọn, chính xác,
   căn cứ vào "KHO TRI THỨC" được cung cấp. Nếu kho tri thức không đủ thông tin,
   hãy ghi câu trả lời là "Vui lòng liên hệ Phòng Tuyển sinh để biết thông tin chi tiết.".
3. Phân loại mỗi FAQ vào một trong các nhóm: "Ngành & Chương trình", "Học phí & Học bổng",
   "Phương thức xét tuyển", "Hồ sơ & Thủ tục", "Đời sống sinh viên", "Khác".

Trả kết quả là **một mảng JSON hợp lệ** (không kèm văn bản nào khác) theo định dạng:
[
  { "question": "...", "answer": "...", "category": "...", "topic_summary": "..." }
]
Tối đa 10 FAQ. Bằng tiếng Việt.`;

export async function POST(req: NextRequest) {
  if (!(await requireAdmin(req))) return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  const db = adminDb();

  // Pull recent user messages from the last 30 days, capped to 500.
  const cutoff = Date.now() - 30 * 24 * 60 * 60 * 1000;
  const convs = await db
    .collection("conversations")
    .where("lastMessageAt", ">=", cutoff)
    .orderBy("lastMessageAt", "desc")
    .limit(200)
    .get();

  const questions: string[] = [];
  for (const c of convs.docs) {
    const msgs = await c.ref
      .collection("messages")
      .where("role", "==", "user")
      .orderBy("createdAt", "desc")
      .limit(5)
      .get();
    for (const m of msgs.docs) {
      const content = String(m.get("content") || "").trim();
      if (content && content.length > 5 && content.length < 600) questions.push(content);
      if (questions.length >= 500) break;
    }
    if (questions.length >= 500) break;
  }

  if (questions.length === 0) {
    return NextResponse.json({
      error: "Chưa có câu hỏi nào trong 30 ngày qua để tổng hợp.",
    }, { status: 400 });
  }

  // Pull KB to ground answers.
  const kbSnap = await db.collection("knowledge").orderBy("updatedAt", "desc").limit(60).get();
  const kbBlock = kbSnap.docs
    .map((d) => {
      const v = d.data();
      return `### ${v.title} (${v.category || "Tổng quát"})\n${String(v.content || "").slice(0, 1200)}`;
    })
    .join("\n\n")
    .slice(0, 16_000);

  const userMsg = `KHO TRI THỨC:\n${kbBlock || "(trống)"}\n\nDANH SÁCH CÂU HỎI GẦN ĐÂY (${questions.length}):\n${questions
    .map((q, i) => `${i + 1}. ${q.replace(/\n+/g, " ")}`)
    .join("\n")
    .slice(0, 14_000)}`;

  const claude = getClaude();
  const completion = await claude.messages.create({
    model: CLAUDE_MODEL,
    max_tokens: 4000,
    system: SYSTEM,
    messages: [{ role: "user", content: userMsg }],
  });

  const text = completion.content
    .filter((c): c is { type: "text"; text: string } => c.type === "text")
    .map((c) => c.text)
    .join("\n");

  const json = extractJsonArray(text);
  if (!json) {
    return NextResponse.json({ error: "Không phân tích được JSON từ AI", raw: text }, { status: 500 });
  }

  const now = Date.now();
  const created: { id: string; question: string }[] = [];
  for (const item of json.slice(0, 10) as GeneratedFaq[]) {
    if (!item?.question || !item?.answer) continue;
    // Avoid duplicates: skip if a similar published question already exists.
    const dup = await db
      .collection("faqs")
      .where("question", "==", item.question)
      .limit(1)
      .get();
    if (!dup.empty) continue;

    const ref = await db.collection("faqs").add({
      question: item.question.slice(0, 500),
      answer: item.answer.slice(0, 8000),
      category: (item.category || "Khác").slice(0, 100),
      clickCount: 0,
      published: false, // Admin reviews before publishing
      generatedAt: now,
      createdAt: now,
      updatedAt: now,
      autoGenerated: true,
    });
    created.push({ id: ref.id, question: item.question });
  }

  return NextResponse.json({ analyzedQuestions: questions.length, created });
}

function extractJsonArray(text: string): unknown[] | null {
  const match = text.match(/\[[\s\S]*\]/);
  if (!match) return null;
  try {
    const parsed = JSON.parse(match[0]);
    return Array.isArray(parsed) ? parsed : null;
  } catch {
    return null;
  }
}
